name: streamlit_data
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.13.9=hc7d8306_100_cp313
  - python_abi=3.13=1_cp313
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py313hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - plotly=6.4.0
  - pip:
      - altair==5.5.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.3
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.60.1
      - frozendict==2.4.7
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - multitasking==0.0.12
      - narwhals==2.11.0
      - numpy==2.3.4
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - peewee==3.18.3
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.4.0
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - seaborn==0.13.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8
      - streamlit==1.51.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - websockets==15.0.1
      - yfinance==0.2.66
prefix: /Users/dmitrijpavlov/miniforge3/envs/streamlit_data
